env: "s"

env_args:
  key: "replenishment_efficient_env-v0"
  map_name: "sku200.2_stores.standard"
  n_agents: 2
  task_type: "sku200.2_stores.standard"
  mode: train
  time_limit: 100
  reward: "reward2"
  