env:
  start_date: 2018/7/1
  end_date: 2021/10/30
  horizon: 100
  lookback_len: 21
  integerization_sku: True
  storage_capacity: 277800
  initial_balance: 0

sku:
  sku_list: ReplenishmentEnv/data/sku2778/sku2778.sku_list.csv
  dynamic_info: 
    - name: demand
      file: ReplenishmentEnv/data/sku2778/sku2778.demand.csv
    - name: selling_price
      file: ReplenishmentEnv/data/sku2778/sku2778.selling_price.csv
    - name: procurement_cost
      file: ReplenishmentEnv/data/sku2778/sku2778.procurement_cost.csv
  static_info: ReplenishmentEnv/data/sku2778/sku2778.info.csv
  shared_info:
    order_cost: 10
    volume: 1
    storage_cost: 0.0025
    holding_cost_ratio: 0.00002

profit:
  profit_function: reward2
  backlog_ratio: 0
  excess_ratio: 0.5


reward:
  mode: same_as_profit

action:
  mode: demand_mean_continuous

output_state:
  current_state:
    [selling_price, procurement_cost, vlt, volume, 
    order_cost, replenish, excess, in_stock, in_transit]
  lookback_state:
    [demand]